# Generated by Django 6.0.5 on 2026-05-30 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_options_alter_sale_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Себестоимость 1 шт., руб.')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Себестоимость списания, руб.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='sales.sale', verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'Списание себестоимости',
                'verbose_name_plural': 'Списания себестоимости',
            },
        ),
    ]
