# Generated by Django 6.0.5 on 2026-05-30 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salecostallocation'),
        ('stock', '0003_stockbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='salecostallocation',
            name='stock_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_allocations', to='stock.stockbatch', verbose_name='Партия товара'),
        ),
    ]
