# Generated by Django 6.0.5 on 2026-05-31 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма возврата')),
                ('destination', models.CharField(choices=[('back_to_stock', 'Вернуть на продажу'), ('write_off', 'Списать')], max_length=20, verbose_name='Куда определить товар')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale', verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
            },
        ),
    ]
