# Generated by Django 6.0.5 on 2026-06-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('sales', '0008_alter_sale_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='orders.order', verbose_name='Заказ'),
        ),
    ]
