# Generated by Django 6.0.5 on 2026-06-03 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('sales', '0009_sale_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='orders.orderitem', verbose_name='Позиция заказа'),
        ),
    ]
