# Generated by Django 6.0.5 on 2026-06-03 18:46

import django.db.models.deletion
from django.db import migrations, models


def fill_return_order(apps, schema_editor):
    SaleReturn = apps.get_model('sales', 'SaleReturn')

    for sale_return in SaleReturn.objects.select_related('sale'):
        if sale_return.sale and sale_return.sale.order_id:
            sale_return.order_id = sale_return.sale.order_id
            sale_return.save(update_fields=['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_customer_orderitem_discount_percent_and_more'),
        ('sales', '0010_sale_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.RunPython(fill_return_order, migrations.RunPython.noop),
    ]
