# Generated by Django 6.0.5 on 2026-05-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_manualsupply_alter_manualsupplyitem_supply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='manufacturer',
        ),
    ]
