# Generated by Django 6.0.5 on 2026-06-03 17:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_product_image_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Имя клиента')),
                ('telegram_username', models.CharField(blank=True, max_length=255, verbose_name='Telegram username')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('waiting_payment', 'Ожидает оплату'), ('paid', 'Оплачен'), ('sold', 'Продажа проведена'), ('shipped', 'Отправлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=30, verbose_name='Статус')),
                ('customer_comment', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('internal_comment', models.TextField(blank=True, verbose_name='Внутренний комментарий')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Сумма заказа')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('tracking_number', models.CharField(blank=True, max_length=255, verbose_name='Трек-номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Цена на момент заказа')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Сумма позиции')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
