# Generated by Django 6.0.5 on 2026-06-03 18:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def fill_unit_price_after_discount(apps, schema_editor):
    OrderItem = apps.get_model('orders', 'OrderItem')

    for item in OrderItem.objects.all():
        item.unit_price_after_discount = item.unit_price
        item.total_price = item.unit_price * item.quantity
        item.save(update_fields=['unit_price_after_discount', 'total_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Скидка, %'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price_after_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Цена со скидкой'),
        ),
        migrations.RunPython(fill_unit_price_after_discount, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('waiting_payment', 'Ожидает оплату'), ('paid', 'Оплачен'), ('sold', 'Продажа проведена'), ('shipped', 'Отправлен'), ('cancelled', 'Отменен')], default='new', max_length=30, verbose_name='Статус'),
        ),
    ]
