# Generated by Django 6.0.5 on 2026-05-30 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_description_and_more'),
        ('stock', '0002_alter_stockmovement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество в партии')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Себестоимость 1 шт., руб.')),
                ('remaining_quantity', models.PositiveIntegerField(verbose_name='Остаток в партии')),
                ('source_type', models.CharField(max_length=50, verbose_name='Тип источника')),
                ('source_id', models.PositiveBigIntegerField(verbose_name='ID источника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Партия товара',
                'verbose_name_plural': 'Партии товаров',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
