# Generated by Django 6.0.5 on 2026-05-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockbatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockbatch',
            options={'ordering': ('created_at', 'id'), 'verbose_name': 'партию товара', 'verbose_name_plural': 'Партии товаров'},
        ),
    ]
