# Generated by Django 6.0.5 on 2026-06-01 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_description_and_more'),
        ('stock', '0004_alter_stockbatch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('released', 'Снят')], default='active', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Снято')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'резерв',
                'verbose_name_plural': 'Резервы',
            },
        ),
        migrations.CreateModel(
            name='StockReservationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='stock.stockreservation', verbose_name='Резерв')),
                ('stock_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_allocations', to='stock.stockbatch', verbose_name='Партия товара')),
            ],
            options={
                'verbose_name': 'Резерв из партии',
                'verbose_name_plural': 'Резервы из партий',
            },
        ),
        migrations.CreateModel(
            name='StockWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('reason', models.CharField(choices=[('defect', 'Брак'), ('damage', 'Повреждение'), ('loss', 'Утеря'), ('inventory_shortage', 'Недостача при инвентаризации'), ('other', 'Другое')], max_length=30, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'списание',
                'verbose_name_plural': 'Списания',
            },
        ),
        migrations.CreateModel(
            name='StockWriteOffAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Себестоимость 1 шт., руб.')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Себестоимость списания, руб.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('stock_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_off_allocations', to='stock.stockbatch', verbose_name='Партия товара')),
                ('write_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='stock.stockwriteoff', verbose_name='Списание')),
            ],
            options={
                'verbose_name': 'Списание из партии',
                'verbose_name_plural': 'Списания из партий',
            },
        ),
    ]
